on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  test:
    name: flutter widget test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: dart pub get
      - run: dart analyze
      - run: dart test
